name: Run Sample Loc Map

on:
  workflow_dispatch:

jobs:
  run-sample-loc-map:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up cached uv
      uses: hynek/setup-cached-uv@v2

    - name: Run sample-loc-map
      run: uv run sample-loc-map